# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Tree",
    "make_unit",
]

@typing.final
class Tree:
    def add(self, key: builtins.int, val: typing.Any) -> Tree: ...
    def search(self, key: builtins.int) -> tuple: ...

def make_unit(key: builtins.int, val: typing.Any) -> Tree: ...

