# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "fib",
    "fib_detached",
]

def fib(val: builtins.int) -> builtins.int: ...

def fib_detached(val: builtins.int) -> builtins.int: ...

